# Generated by Django 5.2.16 on 2026-07-15 08:36

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("aggregate_type", models.CharField(max_length=100)),
                ("aggregate_id", models.CharField(db_index=True, max_length=64)),
                (
                    "payload",
                    models.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published", models.BooleanField(db_index=True, default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                "db_table": "outbox_messages",
                "indexes": [
                    models.Index(
                        fields=["published", "created_at"],
                        name="outbox_mess_publish_00afa2_idx",
                    )
                ],
            },
        ),
    ]
