# Generated by Django 5.2.16 on 2026-07-09 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_months', models.PositiveSmallIntegerField()),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SCORING', 'Scoring'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='products.creditproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_applications',
            },
        ),
        migrations.CreateModel(
            name='ScoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_result', to='applications.creditapplication')),
            ],
            options={
                'db_table': 'scoring_results',
            },
        ),
        migrations.AddConstraint(
            model_name='creditapplication',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='application_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='creditapplication',
            constraint=models.CheckConstraint(condition=models.Q(('term_months__gte', 1)), name='application_term_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='scoringresult',
            constraint=models.CheckConstraint(condition=models.Q(('score__lte', 1000)), name='scoring_score_lte_1000'),
        ),
    ]
