# DOC 5 §14, Roadmap Этап 5 п.14: partition audit_logs by month on created_at
# (fastest-growing table alongside transactions). Postgres can't ALTER an
# existing table into PARTITION BY RANGE — it must be created that way — so
# this rebuilds the table via raw SQL (preserving existing rows) while
# `state_operations` tells Django's migration state about the new field
# shape (composite PK) without Django trying to emit its own ALTER TABLE for
# it. See apps.audit.models.AuditLog's docstring for the id/sequence design,
# and apps.audit.management.commands.create_future_partitions for how future
# months get provisioned ahead of time (wired into CELERY_BEAT_SCHEDULE).
import django.db.models.expressions
from django.db import migrations, models

CREATE_PARTITIONED_TABLE = """
ALTER TABLE audit_logs RENAME TO audit_logs_old;

-- The old `id bigint GENERATED BY DEFAULT AS IDENTITY` column already owns a
-- Postgres-created sequence named audit_logs_id_seq (identity sequences keep
-- their original name across ALTER TABLE ... RENAME). Move it out of the way
-- so our replacement sequence of the same name can be created; it gets
-- dropped automatically when audit_logs_old is dropped below (identity
-- sequences are owned-by-column and cascade with their table).
ALTER SEQUENCE audit_logs_id_seq RENAME TO audit_logs_id_seq_old;

CREATE SEQUENCE audit_logs_id_seq;

CREATE TABLE audit_logs (
    id bigint NOT NULL DEFAULT nextval('audit_logs_id_seq'),
    actor_id bigint NULL,
    action varchar(60) NOT NULL,
    object_type varchar(40) NOT NULL,
    object_id bigint NOT NULL,
    changes jsonb NOT NULL,
    ip_address inet NULL,
    created_at timestamptz NOT NULL,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

ALTER SEQUENCE audit_logs_id_seq OWNED BY audit_logs.id;

CREATE TABLE audit_logs_default PARTITION OF audit_logs DEFAULT;

DO $$
DECLARE
    start_month date := date_trunc('month', now())::date - interval '1 month';
    i int;
    part_start date;
    part_end date;
    part_name text;
BEGIN
    FOR i IN 0..2 LOOP
        part_start := (start_month + (i || ' month')::interval)::date;
        part_end := (part_start + interval '1 month')::date;
        part_name := 'audit_logs_' || to_char(part_start, 'YYYY_MM');
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF audit_logs FOR VALUES FROM (%L) TO (%L)',
            part_name, part_start, part_end
        );
    END LOOP;
END $$;

-- Defensive: a prior reverse-then-forward cycle of this migration recreates
-- the plain (non-partitioned) table with these same explicit index names
-- (see DROP_PARTITIONED_TABLE below), which would otherwise collide here
-- since renaming audit_logs_old doesn't rename its indexes.
DROP INDEX IF EXISTS audit_logs_action_idx;
DROP INDEX IF EXISTS audit_logs_actor_id_idx;
DROP INDEX IF EXISTS audit_logs_object_type_object_id_idx;

CREATE INDEX audit_logs_action_idx ON audit_logs (action);
CREATE INDEX audit_logs_actor_id_idx ON audit_logs (actor_id);
CREATE INDEX audit_logs_object_type_object_id_idx ON audit_logs (object_type, object_id);

ALTER TABLE audit_logs
    ADD CONSTRAINT audit_logs_actor_id_fk_users_id
    FOREIGN KEY (actor_id) REFERENCES users (id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

INSERT INTO audit_logs (id, actor_id, action, object_type, object_id, changes, ip_address, created_at)
SELECT id, actor_id, action, object_type, object_id, changes, ip_address, created_at FROM audit_logs_old;

SELECT setval('audit_logs_id_seq', COALESCE((SELECT MAX(id) FROM audit_logs), 0) + 1, false);

DROP TABLE audit_logs_old;
"""

DROP_PARTITIONED_TABLE = """
ALTER TABLE audit_logs RENAME TO audit_logs_partitioned;

-- Same sequence-name collision as CREATE_PARTITIONED_TABLE, in reverse: the
-- bigserial column below would try to create audit_logs_id_seq itself.
ALTER SEQUENCE audit_logs_id_seq RENAME TO audit_logs_id_seq_partitioned;
-- Renaming a table does not rename its indexes — rename these out of the
-- way too so CREATE INDEX below can reuse the names.
ALTER INDEX audit_logs_action_idx RENAME TO audit_logs_action_idx_partitioned;
ALTER INDEX audit_logs_actor_id_idx RENAME TO audit_logs_actor_id_idx_partitioned;
ALTER INDEX audit_logs_object_type_object_id_idx RENAME TO audit_logs_object_type_object_id_idx_partitioned;

CREATE TABLE audit_logs (
    id bigserial PRIMARY KEY,
    actor_id bigint NULL REFERENCES users (id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    action varchar(60) NOT NULL,
    object_type varchar(40) NOT NULL,
    object_id bigint NOT NULL,
    changes jsonb NOT NULL,
    ip_address inet NULL,
    created_at timestamptz NOT NULL
);

CREATE INDEX audit_logs_action_idx ON audit_logs (action);
CREATE INDEX audit_logs_actor_id_idx ON audit_logs (actor_id);
CREATE INDEX audit_logs_object_type_object_id_idx ON audit_logs (object_type, object_id);

INSERT INTO audit_logs (id, actor_id, action, object_type, object_id, changes, ip_address, created_at)
SELECT id, actor_id, action, object_type, object_id, changes, ip_address, created_at FROM audit_logs_partitioned;

SELECT setval(pg_get_serial_sequence('audit_logs', 'id'), COALESCE((SELECT MAX(id) FROM audit_logs), 0) + 1, false);

DROP TABLE audit_logs_partitioned CASCADE;
DROP SEQUENCE IF EXISTS audit_logs_id_seq_partitioned;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="auditlog",
                    name="pk",
                    field=models.CompositePrimaryKey(
                        "id",
                        "created_at",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="auditlog",
                    name="id",
                    field=models.BigIntegerField(
                        db_default=django.db.models.expressions.RawSQL(
                            "nextval('audit_logs_id_seq')", []
                        ),
                        editable=False,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=CREATE_PARTITIONED_TABLE,
                    reverse_sql=DROP_PARTITIONED_TABLE,
                ),
            ],
        ),
    ]
