# Generated by Django 5.2.16 on 2026-07-11 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_document'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='creditapplication',
            index=models.Index(fields=['status', 'submitted_at'], name='credit_appl_status_25c730_idx'),
        ),
        migrations.AddIndex(
            model_name='creditapplication',
            index=models.Index(fields=['user', 'status'], name='credit_appl_user_id_1cf58f_idx'),
        ),
    ]
