# Generated by Django 5.2.16 on 2026-07-14 13:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_creditapplication_composite_indexes"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="creditapplication",
            index=models.Index(
                condition=models.Q(("status", "MANUAL_REVIEW")),
                fields=["submitted_at"],
                name="idx_apps_manual_review_queue",
            ),
        ),
    ]
