# Generated by Django 5.2.16 on 2026-07-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_term_months', models.PositiveSmallIntegerField()),
                ('max_term_months', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'credit_products',
                'indexes': [models.Index(fields=['is_active', 'slug'], name='credit_prod_is_acti_2fdd7e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_amount__gte', models.F('min_amount'))), name='max_gte_min_amount'), models.CheckConstraint(condition=models.Q(('max_term_months__gte', models.F('min_term_months'))), name='max_gte_min_term'), models.CheckConstraint(condition=models.Q(('interest_rate__gte', 0), ('interest_rate__lte', 100)), name='rate_0_100')],
            },
        ),
    ]
