# Generated by Django 5.2.16 on 2026-07-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["loan", "created_at"], name="transaction_loan_id_71b421_idx"
            ),
        ),
    ]
