# DOC 5 §14, Roadmap Этап 5 п.14: partition transactions by month on
# created_at (the fastest-growing ledger table). Postgres can't ALTER an
# existing table into PARTITION BY RANGE — it must be created that way — so
# this rebuilds the table via raw SQL (preserving existing rows) while
# `state_operations` tells Django's migration state about the new field
# shape (composite PK, idempotency_key's widened uniqueness) without Django
# trying to emit its own ALTER TABLE for it. See
# apps.lending.models.Transaction's docstring for the id/sequence design and
# the idempotency_key trade-off, and
# apps.audit.management.commands.create_future_partitions for how future
# months get provisioned ahead of time (wired into CELERY_BEAT_SCHEDULE;
# shared across both partitioned tables via a table-name argument).
import django.db.models.expressions
from django.db import migrations, models

CREATE_PARTITIONED_TABLE = """
ALTER TABLE transactions RENAME TO transactions_old;

-- The old `id bigint GENERATED BY DEFAULT AS IDENTITY` column already owns a
-- Postgres-created sequence named transactions_id_seq (identity sequences
-- keep their original name across ALTER TABLE ... RENAME). Move it out of
-- the way so our replacement sequence of the same name can be created; it
-- gets dropped automatically when transactions_old is dropped below
-- (identity sequences are owned-by-column and cascade with their table).
ALTER SEQUENCE transactions_id_seq RENAME TO transactions_id_seq_old;

CREATE SEQUENCE transactions_id_seq;

CREATE TABLE transactions (
    id bigint NOT NULL DEFAULT nextval('transactions_id_seq'),
    loan_id bigint NOT NULL,
    type varchar(20) NOT NULL,
    amount numeric(12, 2) NOT NULL,
    balance_after numeric(12, 2) NOT NULL,
    created_at timestamptz NOT NULL,
    idempotency_key varchar(64) NULL,
    PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

ALTER SEQUENCE transactions_id_seq OWNED BY transactions.id;

CREATE TABLE transactions_default PARTITION OF transactions DEFAULT;

DO $$
DECLARE
    start_month date := date_trunc('month', now())::date - interval '1 month';
    i int;
    part_start date;
    part_end date;
    part_name text;
BEGIN
    FOR i IN 0..2 LOOP
        part_start := (start_month + (i || ' month')::interval)::date;
        part_end := (part_start + interval '1 month')::date;
        part_name := 'transactions_' || to_char(part_start, 'YYYY_MM');
        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF transactions FOR VALUES FROM (%L) TO (%L)',
            part_name, part_start, part_end
        );
    END LOOP;
END $$;

-- Defensive: a prior reverse-then-forward cycle of this migration recreates
-- the plain (non-partitioned) table with these same explicit index names
-- (see DROP_PARTITIONED_TABLE below), which would otherwise collide here
-- since renaming transactions_old doesn't rename its indexes.
DROP INDEX IF EXISTS transactions_loan_id_idx;
DROP INDEX IF EXISTS transactions_loan_id_created_at_idx;
DROP INDEX IF EXISTS transactions_idempotency_key_created_at_key;

CREATE INDEX transactions_loan_id_idx ON transactions (loan_id);
CREATE INDEX transactions_loan_id_created_at_idx ON transactions (loan_id, created_at);
CREATE UNIQUE INDEX transactions_idempotency_key_created_at_key
    ON transactions (idempotency_key, created_at);

ALTER TABLE transactions
    ADD CONSTRAINT transactions_loan_id_fk_loans_id
    FOREIGN KEY (loan_id) REFERENCES loans (id)
    DEFERRABLE INITIALLY DEFERRED;

INSERT INTO transactions (id, loan_id, type, amount, balance_after, created_at, idempotency_key)
SELECT id, loan_id, type, amount, balance_after, created_at, idempotency_key FROM transactions_old;

SELECT setval('transactions_id_seq', COALESCE((SELECT MAX(id) FROM transactions), 0) + 1, false);

DROP TABLE transactions_old;
"""

DROP_PARTITIONED_TABLE = """
ALTER TABLE transactions RENAME TO transactions_partitioned;

-- Same sequence-name collision as CREATE_PARTITIONED_TABLE, in reverse: the
-- bigserial column below would try to create transactions_id_seq itself.
ALTER SEQUENCE transactions_id_seq RENAME TO transactions_id_seq_partitioned;
-- Renaming a table does not rename its indexes — rename these out of the
-- way too so CREATE INDEX below can reuse the names.
ALTER INDEX transactions_loan_id_idx RENAME TO transactions_loan_id_idx_partitioned;
ALTER INDEX transactions_loan_id_created_at_idx RENAME TO transactions_loan_id_created_at_idx_partitioned;

CREATE TABLE transactions (
    id bigserial PRIMARY KEY,
    loan_id bigint NOT NULL REFERENCES loans (id) DEFERRABLE INITIALLY DEFERRED,
    type varchar(20) NOT NULL,
    amount numeric(12, 2) NOT NULL,
    balance_after numeric(12, 2) NOT NULL,
    created_at timestamptz NOT NULL,
    idempotency_key varchar(64) NULL UNIQUE
);

CREATE INDEX transactions_loan_id_idx ON transactions (loan_id);
CREATE INDEX transactions_loan_id_created_at_idx ON transactions (loan_id, created_at);

INSERT INTO transactions (id, loan_id, type, amount, balance_after, created_at, idempotency_key)
SELECT id, loan_id, type, amount, balance_after, created_at, idempotency_key FROM transactions_partitioned;

SELECT setval(pg_get_serial_sequence('transactions', 'id'), COALESCE((SELECT MAX(id) FROM transactions), 0) + 1, false);

DROP TABLE transactions_partitioned CASCADE;
DROP SEQUENCE IF EXISTS transactions_id_seq_partitioned;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("lending", "0002_index_optimizations"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="transaction",
                    name="pk",
                    field=models.CompositePrimaryKey(
                        "id",
                        "created_at",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="transaction",
                    name="id",
                    field=models.BigIntegerField(
                        db_default=django.db.models.expressions.RawSQL(
                            "nextval('transactions_id_seq')", []
                        ),
                        editable=False,
                    ),
                ),
                migrations.AlterField(
                    model_name="transaction",
                    name="idempotency_key",
                    field=models.CharField(blank=True, max_length=64, null=True),
                ),
                migrations.AddConstraint(
                    model_name="transaction",
                    constraint=models.UniqueConstraint(
                        fields=("idempotency_key", "created_at"),
                        name="unique_transaction_idempotency_key",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=CREATE_PARTITIONED_TABLE,
                    reverse_sql=DROP_PARTITIONED_TABLE,
                ),
            ],
        ),
    ]
